### PR TITLE
Improve thread synchronization

### LINKED ISSUE #86: Async await for controller responses
Currently, the behavior of the controller server and the environment step is a bit hacky.  Basically, the HTTP request from the emulator to the controller server to request the current controller state needs to wait until the agent has acted in the environment (step). Likewise, the step call needs to wait to return to the agent until the emulator has read the latest controller state. They do this by toggling the value of `hold_response` and sleeping in a busy wait until the other side toggles its value back.

This should be replaced with a proper, non-blocking async await (see [here](https://docs.python.org/3/library/asyncio-sync.html) for some possibilities). Depending on the approach, this may be dependent on the Python3 upgrade (#81). Obviously, this will need thorough testing as well.

See [`send_controls`](https://github.com/bzier/gym-mupen64plus/blob/339573fe6169732fb53a3fd02dd896cb53fbcdef/gym_mupen64plus/envs/mupen64plus_env.py#L419) and [`do_GET`](https://github.com/bzier/gym-mupen64plus/blob/339573fe6169732fb53a3fd02dd896cb53fbcdef/gym_mupen64plus/envs/mupen64plus_env.py#L453)

### PR DESCRIPTION
**Pull request by bzier**
Improve the thread synchronization in the `ControllerHTTPServer`, to replace the busy wait loop that was used previously with the use of `threading.Event()` for synchronization. Updated the documentation and added several diagrams to help make the implementation clear.

Fixes #86 

Because the diagrams don't show by default in the diff, including them here as well:

[Thread Synchronization Object Diagram](https://github.com/bzier/gym-mupen64plus/raw/ab5f02ad983b882f623bef47f68b4ace292bafa2/docs/threadSyncObjectDiagram.png)

[Thread Synchronization Sequence Diagram (A)")](https://github.com/bzier/gym-mupen64plus/raw/ab5f02ad983b882f623bef47f68b4ace292bafa2/docs/threadSyncSeqDiagramA.png)

[Thread Synchronization Sequence Diagram (B)")](https://github.com/bzier/gym-mupen64plus/raw/ab5f02ad983b882f623bef47f68b4ace292bafa2/docs/threadSyncSeqDiagramB.png)

### CODE REVIEW

**Comment by roclark** [comment]
This looks incredible! So if I understand correctly, this will provide a more direct correlation between what is happening in the emulator and what the agent sees of the environment, causing more stable models?

**Comment by bzier** [comment]
@roclark unfortunately you shouldn't really see any impact to the models. The code was already synchronized in the same place, but was being done by repeatedly checking a boolean value and sleeping, in other words a "busy wait". This is inefficient as the thread has to constantly wake up to check the value. Switching to using [`threading.Events`](https://docs.python.org/3/library/threading.html#event-objects) means it can use the underlying threading system to wait until the event fires, rather than having to do the busy loop.

It may spare some CPU cycles, but the behavior of the environment should be no different.

**Review by kevinhughes27 — APPROVED** [review]
Looks good to me! I didn't go super deep but I see what you're doing and the sleep loop is removed. I would be curious how much faster this ends up being! even a few cycles probably makes a difference if you're training an agent for a long time.

**Comment by bzier** [comment]
Unfortunately, I haven't seen a significant speed-up in my testing so far in terms of wall clock time or env steps per second. However, I did attempt to explicitly measure CPU utilization with a simple script. Running it several times before/after the change shows that this does improve things.

The script extracts the CPU clocks ticks scheduled in user & system/kernel mode from the `/proc/self/stat` file. After starting, it sleeps for 10s to show that negligible CPU time is spent. Then it initializes the gym environment and captures how many ticks were taken. Then it sleeps again for 10s, while taking no action in the environment. Again it captures the ticks.

When running this with the old code, there are about 20 user ticks and 40 system ticks taken during the second sleep (numbers vary slightly run-to-run). Extending the second sleep to 100s, the difference is 230 user ticks and 370 system ticks (approx. numbers - only from one run). With the code change in this PR, no ticks are taken during the sleep time, whether 10s or 100s.

Because the old code was busy waiting for the controls to be updated, even taking no action in the environment, every millisecond the thread is waking from sleep to check if they are there. While this isn't computationally expensive, it is unnecessary and does result in more ticks used by the application. I tested while taking action in the environment and saw a similarly higher number of ticks for the old code than the new as well, but then isolated things a bit further by simply sleeping.

I think the reason that this hasn't had much impact on steps per second is that the code was checking for updated controls every millisecond. At most, the latency added between the action in the environment and the controls response being sent back would have been 1 millisecond, and often maybe less (if we had already been asleep for 0.9 ms when the controls were updated). Since there are many more limiting factors (the actual training algorithm, the neural network processing time, the HTTP response time, etc), I don't think the time was significantly affected. However, I do believe that the change lightens the load on the CPU, and makes things more efficient - not to mention cleaner/clearer code (in my opinion), which is always great :)

## Test Script:
```py
#!/bin/python
import time

out_lines = []
def appendLineWithTicks(message):
    global out_lines
    with open('/proc/self/stat') as f:
        stat = f.readline().split()
        out_lines += [(message + " (user ticks: {0}; sys ticks: {1})").format(stat[13], stat[14])]

appendLineWithTicks("Process start")

time.sleep(10)
appendLineWithTicks("After 10s sleep")

import gym, gym_mupen64plus
env = gym.make('Mario-Kart-Luigi-Raceway-v0')
obs = env.reset()
appendLineWithTicks("After gym env")

time.sleep(10)
appendLineWithTicks("After 10s sleep")

env.close()

for line in out_lines: print(line)
```

## Subset of the output:
```
## 20210130.4 - quizzical_golick (container running the previous version)

# run 1:
Process start (user ticks: 0; sys ticks: 1)
After 10s sleep (user ticks: 1; sys ticks: 1)
After gym env (user ticks: 51; sys ticks: 103)
After 10s sleep (user ticks: 77; sys ticks: 140)

# run 2:
Process start (user ticks: 1; sys ticks: 3)
After 10s sleep (user ticks: 1; sys ticks: 3)
After gym env (user ticks: 99; sys ticks: 140)
After 10s sleep (user ticks: 120; sys ticks: 187)

# run w/100s sleep:
Process start (user ticks: 0; sys ticks: 1)
After 10s sleep (user ticks: 0; sys ticks: 1)
After gym env (user ticks: 54; sys ticks: 111)
After 10s sleep (user ticks: 284; sys ticks: 487)

## 20210207.01 - flamboyant_northcutt (container running the new code)

# run 1:
Process start (user ticks: 0; sys ticks: 1)
After 10s sleep (user ticks: 0; sys ticks: 1)
After gym env (user ticks: 52; sys ticks: 91)
After 10s sleep (user ticks: 52; sys ticks: 92)

# run 2:
Process start (user ticks: 1; sys ticks: 1)
After 10s sleep (user ticks: 1; sys ticks: 1)
After gym env (user ticks: 79; sys ticks: 69)
After 10s sleep (user ticks: 79; sys ticks: 69)

# run w/100s sleep:
Process start (user ticks: 0; sys ticks: 0)
After 10s sleep (user ticks: 0; sys ticks: 0)
After gym env (user ticks: 46; sys ticks: 79)
After 10s sleep (user ticks: 47; sys ticks: 79)
```

## Notes:
For reference regarding the CPU ticks, see the [proc man page](https://man7.org/linux/man-pages/man5/proc.5.html). Unfortunately, the sections are not directly linkable, but you can do a 'find in page' to get to the sections (searching the path itself returns lots of matches throughout the page):
* `/proc/self` - Find 'refers to the process accessing'
* `/proc/[pid]/stat`- Find 'Status information about the process'

**Pull request merged**
