### PR TITLE
Add docker-compose & example script

### PR DESCRIPTION
**Pull request by bzier**
- Add a docker compose file for running each of the components/processes in containers.
- Add an example script, which demonstrates how to run a simple agent and verify that things are up and running successfully.
- Update the input bot version to take advantage of it's configurability.
- Refactor the main env to allow for the internally started emulator, or for one external to the process.

### CODE REVIEW

**Comment by sgallese** [comment]
When checking out this branch and running the following code, I encounter the below issue
`docker-compose up --build -d`

```
Pulling xvfbsrv (gym_mupen64plus:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling xvfbsrv (gym_mupen64plus:)...
ERROR: pull access denied for gym_mupen64plus, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by bzier** [comment]
Hi @sgallese, I actually haven't tried running the code in this branch in quite some time. Looking at the docker compose file, my guess is that it may require you to build the base gym-mupen64plus image before trying to run the compose command. I probably already had the image built when I created this file, so it probably worked fine, but if you are running it from scratch, it may fail. I can try to take a closer look this week and see if I can come up with anything more specific for you.

**Comment by sgallese** [comment]
Good points @bzier.
I created the docker image first like so:
`docker build -t bz/gym-mupen64plus:0.0.5 .`

**Docker image is now created**
➜  gym-mupen64plus git:(add-docker-compose) ✗ docker images
REPOSITORY           TAG       IMAGE ID       CREATED         SIZE
bz/gym-mupen64plus   0.0.5     74ce76ed63ae   3 minutes ago   1.08GB

I then had to modify the docker-compose.yml file by replacing all instances of
`image: gym-mupen64plus`
with
`image: bz/gym-mupen64plus:0.0.5`

I also mounted my ROM folder by adding a volumes path under emulator: (below images:) in docker-compose.yml
    volumes:
      - /Path/To/My/Rom/Folder:/src/gym-mupen64plus/gym_mupen64plus/ROMs

I then downloaded VNC Viewer and was able to see Mario when connected to localhost. Woohoo!

**Summary**
Yes, the README should to create the image first and then run Docker Compose.

Ideally we don't have to specify an image version in docker-compose.yml.
But I couldn't figure out how to use something like `image: bz/gym-mupen64plus:latest`

And ideally we can set the /Path/To/My/Rom/Folder somewhere easily.
I saw Docker Compose supports .env files, but this requires Docker Compose 3.4 (currently using 2.3 in the yml file).

If you'd find it helpful, I can open a PR against this branch with the tweaks.
But curious if you know of any smarter ways of accomplishing the above.

**Comment by bzier** [comment]
That's actually exactly what I'm doing [here](https://github.com/bzier/universe-starter-agent/tree/mario-kart-agent#build) in my fork of the universe starter agent. It is using the .env file to specify the image and the path to the rom file(s).

It may be important to note that other project depends on the image from this one. It's docker compose is completely separate, and it actually runs all the processes inside the same container (in each worker). That is in contrast to the docker compose file you've been using here, where each process (xvfb, vnc server, mupen64plus) are each running in their own container. Some day I may try to align these two different approaches, but for now they remain different.

Anyway, I only point it out as a reference. I don't know what the 'smartest' approach is, but I'm happy to review any PRs you want to send. It's always a good thing to make incremental progress.

**Comment by bzier** [comment]
Btw, `latest` is just another tag, so you can update the build statement as `docker build -t bz/gym-mupen64plus:0.0.5  -t bz/gym-mupen64plus:latest .` (see [here](https://docs.docker.com/engine/reference/commandline/build/#tag-an-image--t))

**Comment by sgallese** [comment]
Really appreciate the help @bzier 
Here's what I found helpful to run Docker Compose: https://github.com/bzier/gym-mupen64plus/pull/79

**Comment by bzier** [comment]
Applied several fixes and improvements today. On merge, this PR will close #73 and #80. It will also supersede and close #79 as it incorporates most of the tweaks there.

**Pull request merged**
